config/routes.rb
Assignments::Application.routes.draw do
  get "assignments/new"

  get "sessions/new"
  get "users/blank"
  get "users/buttons"
  get "users/flot"
  get "users/forms"
  get "users/grid"
  get "users/morris"
  get "users/login"
  get "users/morris"
  get "users/notifications"
  get "users/panels_wells"
  get "users/tables"
  get "users/timeline"
  get "users/typography"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#index"
  resources :users
  resources :sessions
  resources :assignments
  
  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :assign_date, :assign_end_date, :description, :is_assign, :name, :assign_type, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :email, :mobile_no, :name, :pan_card_no,:password, :password_confirmation, :password_hash, :password_salt, :subject, :username
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  layout "assignment"
 def index
 	@assignment=Assignment.all
 	
 end
  def new
  	@assign = Assignment.new
  end
  
  def create
  	@assign = Assignment.new(params[:assignment])
  		if @assign.save
    		redirect_to assignments_path, :notice => "Assignment create succesfully!"
  		else
    		render "new"
  		end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	layout "users"
    def new

  	end
  	##########################################################################################	
  	##################################### To Create A new Session ############################
  	##########################################################################################
  	def create
  		user = User.authenticate(params[:email], params[:password])
  		if user
    		session[:user_id] = user.id
    		redirect_to root_url, :notice => "Logged in!"
  		else
    		flash.now.alert = "Invalid email or password"
    		render "new"
  		end
    end
    ##########################################################################################
    ##################################### To destroy  Session ################################
    ##########################################################################################
 	def destroy
    	session[:user_id] = nil
    	redirect_to root_url, :notice => "Logged out!"
 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "users"
  	def new
  		@user = User.new
	end
  def blank
    
  end
  def login
    
  end
  def show
    
  end
	def create
  		@user = User.new(params[:user])
  		if @user.save
    		redirect_to root_url, :notice => "Signed up!"
  		else
    		render "new"
  		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/index.html.erb
<h2 class="text-center">Assignments List</h2>
<hr/>
<%if !@assignment.nil?%>
<div class="table-responsive">
<table class="table table-bordered">
	<tr class="info"><th>Name</th>
	
	<th>Assign</th>
	<th>Assign Name</th>
	<th>Type</th>
	<th>Start Date</th>
	<th>End Date</th>
	<th>Description</th>
   </tr>
<tbody class="table-hover">
<%@assignment.each_with_index do |assign,index|%>

 <tr class="<%if index.even?%>success<%else%>warning<%end%>">
  <td><%=assign.name%></td>
  <td><%=assign.is_assign%></td>
  <td><%if assign.user_id.nil?%>Not Assign <%end%></td>
  <td><%=assign.assign_type%></td>
  <td><%=assign.assign_date%></td>
  <td><%=assign.assign_end_date%></td>
  <td><a hreh="#" class="btn btn-info">view</a></td>
 </tr>
 <%end%>
 <tbody>
</table>
</div>
<%end%>

app/views/assignments/new.html.erb
<div class="container">
	<section id="content">
<h1>Add New Assignment</h1>

<%= form_for @assign do |f| %>
  <% if @assign.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @assign.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %></div><br />
    <div><%= f.text_field :name %></div>
    <div>
    <%= f.label :description %></div><br />
    <div><%= f.text_field :description %></div>
    <div>
    <%= f.label :assign_type %></div><br />
    <div><%= f.text_field :assign_type %></div>
  <div><%= f.submit %></div>
<% end %>

app/views/layouts/_header.html.erb
 <br/>
  <div id="user_nav" class="text-right">
  <% if !current_user.nil? %>

    <span class="text-success">Logged in as <b><%= current_user.name %></b>.</span>
    <%if current_user.is_admin==true and params[:action]!="new"%>
  <%= link_to "Create Assignment",  new_assignment_path ,:class=>"btn btn-primary"%>
  <%end%>
    <%= link_to "Log out", log_out_path ,:class=>"btn btn-primary"%>
  <% else %>
    <%= link_to "Sign up", sign_up_path,:class=>"btn btn-primary"%> or
    <%= link_to "log in", log_in_path ,:class=>"btn btn-primary"%>
  <% end %>
</div>

<br/>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<head>
  <title>Assignments</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render :partial=> '/layouts/header' %>
<%= yield %>
<%= render :partial=> '/layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/assignment.html.erb
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<head>
  <title>Assignments</title>
  <%= stylesheet_link_tag    "bootstrap", "bootstrap-theme", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= render :partial=> '/layouts/header' %>
<%= yield %>
<%= render :partial=> '/layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootsrtap Free Admin Template - SIMINTA | Admin Dashboad Template</title>
    <!-- Core CSS - Include with every page -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="/assets/css/style.css" rel="stylesheet" />
    <link href="/assets/css/main-style.css" rel="stylesheet" />
    <!-- Page-Level CSS -->
    <link href="/assets/plugins/morris/morris-0.4.3.min.css" rel="stylesheet" />
   </head>
<body>
	<%if !current_user.nil?%>
<%= render :partial=> '/layouts/user_header' %>
<%end%>
<%= yield %>
<% if params[:action]=='login' or params[:action]=='new'%>
    <script src="/assets/plugins/jquery-1.10.2.js"></script>
    <script src="/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
<%else%>
    <script src="/assets/plugins/jquery-1.10.2.js"></script>
    <script src="/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/assets/plugins/pace/pace.js"></script>
    <script src="/assets/plugins/morris/raphael-2.1.0.min.js"></script>
    <script src="/assets/plugins/morris/morris.js"></script>
    <script src="/assets/dashboard-demo.js"></script>
<%end%>
</body>
</html>

app/views/users/login.html.erb


<body class="body-Login-back">

    <div class="container">
       
        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center logo-margin ">
              <img src="assets/img/logo.png" alt=""/>
                </div>
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">                  
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

     <!-- Core Scripts - Include with every page -->
    
    
    
</body>


app/views/users/new.html.erb
<div class="container">
	<section id="content">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %></div><br />
    <div><%= f.text_field :name %></div>
    <div>
    <%= f.label :mobile_no %></div><br />
    <div><%= f.text_field :mobile_no %></div>
    <div>
    <%= f.label :email %></div><br />
    <div><%= f.text_field :email %></div>
    <div>
    <%= f.label :pan_card_no %></div><br />
    <div><%= f.text_field :pan_card_no %></div>
    <div>
    <%= f.label :username %></div><br />
    <div><%= f.text_field :username %></div>
  
    <div><%= f.label :password %></div><br />
    <div><%= f.password_field :password %></div>
  
    <div><%= f.label :password_confirmation %></div><br />
    <div><%= f.password_field :password_confirmation %></div>
    <div>
    <%= f.label :subject %></div><br />
    <div><%= f.text_field :subject %></div>
    <div>
    <%= f.label :address %></div><br />
    <div><%= f.text_field :address %></div>
  <div><%= f.submit %></div>
<% end %>